# Generated by Django 4.2.1 on 2023-05-17 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('N4', '0002_delete_vocabulary_delete_vocabularylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyListN4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_number', models.CharField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VocabularyN4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=100)),
                ('nihongo', models.CharField(max_length=100)),
                ('bangla', models.CharField(blank=True, max_length=100, null=True)),
                ('vocabulary_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vocabulary', to='N4.vocabularylistn4')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
