# Generated by Django 4.2.1 on 2023-05-09 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_number', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=100)),
                ('nihongo', models.CharField(max_length=100)),
                ('bangla', models.CharField(blank=True, max_length=100, null=True)),
                ('vocabulary_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vocabulary_list', to='N5.vocabularylist')),
            ],
        ),
    ]
