# Generated by Django 4.2.1 on 2023-05-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('N5', '0002_alter_vocabulary_vocabulary_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VocabularyList',
            new_name='VocabularyListN5',
        ),
        migrations.DeleteModel(
            name='Vocabulary',
        ),
    ]
