# Generated by Django 4.2.1 on 2023-05-17 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('N5', '0003_rename_vocabularylist_vocabularylistn5_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyN5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=100)),
                ('nihongo', models.CharField(max_length=100)),
                ('bangla', models.CharField(blank=True, max_length=100, null=True)),
                ('vocabulary_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vocabulary', to='N5.vocabularylistn5')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
