# Generated by Django 4.2.1 on 2023-05-17 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('N4', '0004_alter_vocabularylistn4_list_number'),
        ('N5', '0005_alter_vocabularylistn5_list_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanjiN5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.CharField(max_length=100, unique=True)),
                ('nihongo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vocabulary', to='N5.vocabularyn5')),
            ],
        ),
        migrations.CreateModel(
            name='KanjiN4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.CharField(max_length=100, unique=True)),
                ('nihongo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vocabulary', to='N4.vocabularyn4')),
            ],
        ),
    ]
